import { useEffect, useMemo, useState } from 'react'
import { Alert, Button, Checkbox, Chip, Dialog, DialogActions, DialogContent, DialogTitle, FormControl, FormControlLabel, InputLabel, LinearProgress, MenuItem, Paper, Select, Stack, TextField, Typography } from '@mui/material'
import { PageShell } from '../components/PageShell'
import { BonusSetEditor } from '../components/forms/BonusSetEditor'
import { loadMasterData } from '../domain/master/loadMasterData'
import { getEnabledElements, getEnabledWeaponTypes, getGroupSkillOptions, getSeriesSkillOptions } from '../domain/master/masterSelectors'
import { createDefaultBonusSet, createOwnedWeaponDraft, MasterOptionsUnavailableError } from '../domain/forms/entityDrafts'
import type { OwnedWeapon, OwnedWeaponStatus, TargetWeapon } from '../domain/models/publicTypes'
import { targetWeaponRepository } from '../db/repositories'
import { EntityFormValidationError, OwnedWeaponCrudService, ReferencedEntityDeleteError, type OwnedWeaponDraft } from '../services/crud/entityCrudServices'

const masterResult = loadMasterData()
const statusLabels: Record<OwnedWeaponStatus, string> = { material: '素材', practical: '実用', ideal: '理想' }

export interface OwnedWeaponsPageDependencies {
  getAll(): Promise<OwnedWeapon[]>
  getTargets(): Promise<TargetWeapon[]>
  save(draft: OwnedWeaponDraft, existing: OwnedWeapon | null): Promise<OwnedWeapon>
  delete(id: OwnedWeapon['id']): Promise<void>
}

function referenceMessage(error: ReferencedEntityDeleteError): string {
  return `参照中のため削除できません: ${error.references.map((reference) => `${reference.kind} ${reference.entityId} (${reference.path})`).join(' / ')}`
}

export function OwnedWeaponsPage({ dependencies }: { dependencies?: OwnedWeaponsPageDependencies }) {
  const defaultService = useMemo(() => masterResult.ok ? new OwnedWeaponCrudService(masterResult.data) : null, [])
  const api = useMemo<OwnedWeaponsPageDependencies | null>(() => dependencies ?? (defaultService ? { getAll: () => defaultService.getAll(), getTargets: () => targetWeaponRepository.getAllTargetWeapons(), save: (draft, existing) => defaultService.save(draft, existing), delete: (id) => defaultService.delete(id) } : null), [defaultService, dependencies])
  const [weapons, setWeapons] = useState<OwnedWeapon[]>([])
  const [targets, setTargets] = useState<TargetWeapon[]>([])
  const [loading, setLoading] = useState(api !== null)
  const [editing, setEditing] = useState<OwnedWeapon | null>(null)
  const [draft, setDraft] = useState<OwnedWeaponDraft | null>(null)
  const [error, setError] = useState<string | null>(api ? null : 'Master Dataが利用できません。')
  const [notice, setNotice] = useState<string | null>(null)
  useEffect(() => { if (!api) return; let active = true; void Promise.all([api.getAll(), api.getTargets()]).then(([loaded, loadedTargets]) => { if (active) { setWeapons(loaded); setTargets(loadedTargets) } }).catch((caught: unknown) => { if (active) setError(caught instanceof Error ? caught.message : '所持武器を読み込めません。') }).finally(() => { if (active) setLoading(false) }); return () => { active = false } }, [api])
  if (!masterResult.ok) return <PageShell title="Owned Weapons" description="所持している巨戟アーティアを管理します。"><Alert severity="error">Master Dataが利用できません。</Alert></PageShell>
  const master = masterResult.data
  const openNew = () => { try { setEditing(null); setDraft(createOwnedWeaponDraft(master)); setError(null) } catch (caught) { setError(caught instanceof Error ? caught.message : '入力選択肢がありません。') } }
  const openEdit = (weapon: OwnedWeapon) => { const { id: _id, createdAt: _createdAt, updatedAt: _updatedAt, ...value } = weapon; void _id; void _createdAt; void _updatedAt; setEditing(weapon); setDraft(structuredClone(value)) }
  const save = async () => { if (!api || !draft) return; if (editing && editing.status !== 'material' && draft.status === 'material' && !window.confirm('この武器を素材扱いに変更します。Plannerで素材候補になる可能性があります。')) return; try { const saved = await api.save(draft, editing); setWeapons((current) => [...current.filter(({ id }) => id !== saved.id), saved]); setDraft(null); setEditing(null); setNotice('所持武器を保存しました。'); setError(null) } catch (caught: unknown) { setError(caught instanceof EntityFormValidationError ? caught.issues.join(' / ') : caught instanceof Error ? caught.message : '保存できません。') } }
  const remove = async (weapon: OwnedWeapon) => { if (!api || !window.confirm(`${weapon.name}を削除しますか？`)) return; try { await api.delete(weapon.id); setWeapons((current) => current.filter(({ id }) => id !== weapon.id)); setNotice('所持武器を削除しました。'); setError(null) } catch (caught: unknown) { setError(caught instanceof ReferencedEntityDeleteError ? referenceMessage(caught) : caught instanceof Error ? caught.message : '削除できません。') } }
  const weaponTypes = getEnabledWeaponTypes(master); const elements = getEnabledElements(master)
  return <PageShell title="Owned Weapons" description="所持している巨戟アーティアを1本ずつ管理します。"><Stack spacing={2}>{loading && <LinearProgress />}{error && <Alert severity="error">{error}</Alert>}{notice && <Alert severity="success">{notice}</Alert>}<Button variant="contained" onClick={openNew}>所持武器を追加</Button>{!loading && weapons.length === 0 && <Alert severity="info">所持武器は未登録です。</Alert>}{weapons.map((weapon) => <Paper key={weapon.id} variant="outlined" sx={{ p: 2 }}><Stack spacing={1}><Stack direction="row" spacing={1}><Typography variant="h3">{weapon.name}</Typography><Chip label={statusLabels[weapon.status]} /><Chip label={weapon.isProtected ? '保護中' : '未保護'} color={weapon.isProtected ? 'success' : 'default'} /></Stack><Typography>{weaponTypes.find(({ id }) => id === weapon.weaponTypeId)?.displayNameJa} / {elements.find(({ id }) => id === weapon.elementId)?.displayNameJa}</Typography><Typography variant="body2">復元ボーナス: {weapon.restorationBonuses.map((bonus) => master.weaponBonusDefinitions.find((definition) => definition.weaponTypeId === weapon.weaponTypeId && definition.bonusTypeId === bonus.bonusTypeId && definition.bonusRankId === bonus.bonusRankId)?.displayNameJa ?? '不明').join('、')}</Typography><Typography variant="body2">シリーズ: {master.seriesSkills.find(({ id }) => id === weapon.seriesSkillId)?.displayNameJa ?? 'なし'} ／ グループ: {master.groupSkills.find(({ id }) => id === weapon.groupSkillId)?.displayNameJa ?? 'なし'}</Typography><Typography variant="body2">関連Target: {weapon.relatedTargetWeaponIds.map((id) => targets.find((target) => target.id === id)?.name ?? '不明').join('、') || 'なし'}</Typography><Stack direction="row" spacing={1}><Button onClick={() => openEdit(weapon)}>編集</Button><Button color="error" onClick={() => void remove(weapon)}>削除</Button></Stack></Stack></Paper>)}
    <Dialog open={draft !== null} onClose={() => setDraft(null)} fullWidth maxWidth="md"><DialogTitle>{editing ? '所持武器を編集' : '所持武器を追加'}</DialogTitle>{draft && <DialogContent><Stack spacing={2} sx={{ pt: 1 }}><TextField label="名前" value={draft.name} required onChange={(event) => setDraft({ ...draft, name: event.target.value })} /><FormControl><InputLabel id="owned-weapon-type">武器種</InputLabel><Select labelId="owned-weapon-type" label="武器種" value={draft.weaponTypeId} onChange={(event) => { try { setDraft({ ...draft, weaponTypeId: event.target.value, restorationBonuses: createDefaultBonusSet(master, event.target.value) }) } catch (caught) { if (caught instanceof MasterOptionsUnavailableError) setError(caught.message) } }}>{weaponTypes.map((type) => <MenuItem key={type.id} value={type.id}>{type.displayNameJa}</MenuItem>)}</Select></FormControl><FormControl><InputLabel id="owned-element">属性</InputLabel><Select labelId="owned-element" label="属性" value={draft.elementId} onChange={(event) => setDraft({ ...draft, elementId: event.target.value })}>{elements.map((element) => <MenuItem key={element.id} value={element.id}>{element.displayNameJa}</MenuItem>)}</Select></FormControl><BonusSetEditor label="復元ボーナス5枠" master={master} weaponTypeId={draft.weaponTypeId} value={draft.restorationBonuses} onChange={(restorationBonuses) => setDraft({ ...draft, restorationBonuses })} />
      <FormControl><InputLabel id="owned-series">シリーズスキル</InputLabel><Select labelId="owned-series" label="シリーズスキル" value={draft.seriesSkillId ?? ''} onChange={(event) => setDraft({ ...draft, seriesSkillId: event.target.value || null })}><MenuItem value="">なし</MenuItem>{getSeriesSkillOptions(master).map((skill) => <MenuItem key={skill.id} value={skill.id}>{skill.displayNameJa}</MenuItem>)}</Select></FormControl><FormControl><InputLabel id="owned-group">グループスキル</InputLabel><Select labelId="owned-group" label="グループスキル" value={draft.groupSkillId ?? ''} onChange={(event) => setDraft({ ...draft, groupSkillId: event.target.value || null })}><MenuItem value="">なし</MenuItem>{getGroupSkillOptions(master).map((skill) => <MenuItem key={skill.id} value={skill.id}>{skill.displayNameJa}</MenuItem>)}</Select></FormControl><FormControl><InputLabel id="owned-status">Status</InputLabel><Select labelId="owned-status" label="Status" value={draft.status} onChange={(event) => setDraft({ ...draft, status: event.target.value as OwnedWeaponStatus })}>{Object.entries(statusLabels).map(([value, label]) => <MenuItem key={value} value={value}>{label}</MenuItem>)}</Select></FormControl><FormControlLabel control={<Checkbox checked={draft.isProtected} onChange={(event) => setDraft({ ...draft, isProtected: event.target.checked })} />} label="保護する" /><Typography variant="subtitle2">関連Target</Typography>{targets.map((target) => <FormControlLabel key={target.id} control={<Checkbox checked={draft.relatedTargetWeaponIds.includes(target.id)} onChange={(event) => setDraft({ ...draft, relatedTargetWeaponIds: event.target.checked ? [...draft.relatedTargetWeaponIds, target.id] : draft.relatedTargetWeaponIds.filter((id) => id !== target.id) })} />} label={target.name} />)}<TextField label="メモ" multiline value={draft.memo ?? ''} onChange={(event) => setDraft({ ...draft, memo: event.target.value || null })} /></Stack></DialogContent>}<DialogActions><Button onClick={() => setDraft(null)}>キャンセル</Button><Button variant="contained" onClick={() => void save()}>保存</Button></DialogActions></Dialog>
  </Stack></PageShell>
}
