import { useEffect, useMemo, useState } from 'react'
import { Alert, Button, Checkbox, Dialog, DialogActions, DialogContent, DialogTitle, FormControl, FormControlLabel, InputLabel, LinearProgress, MenuItem, Paper, Select, Stack, TextField, Typography } from '@mui/material'
import { PageShell } from '../components/PageShell'
import { BonusSetEditor } from '../components/forms/BonusSetEditor'
import { SkillConditionEditor } from '../components/forms/SkillConditionEditor'
import { MasterDataStatusAlert } from '../components/MasterDataStatusAlert'
import { loadMasterData } from '../domain/master/loadMasterData'
import { getEnabledElements, getEnabledWeaponTypes, getRanksForBonusType } from '../domain/master/masterSelectors'
import { createDefaultBonusSet, createTargetWeaponDraft, MasterOptionsUnavailableError } from '../domain/forms/entityDrafts'
import type { AlternativeBonusConditionGroup, BonusCondition, TargetWeapon } from '../domain/models/publicTypes'
import { EntityFormValidationError, ReferencedEntityDeleteError, TargetWeaponCrudService, type TargetWeaponDraft } from '../services/crud/entityCrudServices'
import { getPersistenceReferenceKindLabel } from '../presentation/labels'

const masterResult = loadMasterData()

export interface TargetWeaponsPageDependencies {
  getAll(): Promise<TargetWeapon[]>
  save(draft: TargetWeaponDraft, existing: TargetWeapon | null): Promise<TargetWeapon>
  delete(id: TargetWeapon['id']): Promise<void>
}
function randomItemId() { return globalThis.crypto.randomUUID() }

function deleteReferenceMessage(error: ReferencedEntityDeleteError) {
  return `参照中のため削除できません: ${error.references.map((reference) => `${getPersistenceReferenceKindLabel(reference.kind)}（${reference.entityId}）`).join(' / ')}`
}

export function TargetWeaponsPage({ dependencies }: { dependencies?: TargetWeaponsPageDependencies }) {
  const defaultService = useMemo(() => masterResult.ok ? new TargetWeaponCrudService(masterResult.data) : null, [])
  const api = useMemo<TargetWeaponsPageDependencies | null>(() => dependencies ?? (defaultService ? { getAll: () => defaultService.getAll(), save: (draft, existing) => defaultService.save(draft, existing), delete: (id) => defaultService.delete(id) } : null), [defaultService, dependencies])
  const [targets, setTargets] = useState<TargetWeapon[]>([])
  const [loading, setLoading] = useState(api !== null)
  const [editing, setEditing] = useState<TargetWeapon | null>(null)
  const [draft, setDraft] = useState<TargetWeaponDraft | null>(null)
  const [error, setError] = useState<string | null>(api ? null : 'マスターデータが利用できません。')
  const [notice, setNotice] = useState<string | null>(null)
  useEffect(() => { if (!api) return; let active = true; void api.getAll().then((loaded) => { if (active) setTargets(loaded) }).catch((caught: unknown) => { if (active) setError(caught instanceof Error ? caught.message : '目標武器を読み込めません。') }).finally(() => { if (active) setLoading(false) }); return () => { active = false } }, [api])
  if (!masterResult.ok) return <PageShell title="目標武器" description="欲しい完成武器を管理します。"><Alert severity="error">マスターデータが利用できません。</Alert></PageShell>
  const master = masterResult.data
  const weaponTypes = getEnabledWeaponTypes(master); const elements = getEnabledElements(master)
  const openNew = () => { try { setEditing(null); setDraft(createTargetWeaponDraft(master)); setError(null) } catch (caught) { setError(caught instanceof Error ? caught.message : '入力選択肢がありません。') } }
  const openEdit = (target: TargetWeapon) => { const { id: _id, createdAt: _createdAt, updatedAt: _updatedAt, ...value } = target; void _id; void _createdAt; void _updatedAt; setEditing(target); setDraft(structuredClone(value)) }
  const save = async () => { if (!api || !draft) return; try { const saved = await api.save(draft, editing); setTargets((current) => [...current.filter(({ id }) => id !== saved.id), saved]); setDraft(null); setEditing(null); setNotice('目標武器を保存しました。'); setError(null) } catch (caught: unknown) { setError(caught instanceof EntityFormValidationError ? caught.issues.join(' / ') : caught instanceof Error ? caught.message : '保存できません。') } }
  const remove = async (target: TargetWeapon) => { if (!api || !window.confirm(`${target.name}を削除しますか？`)) return; try { await api.delete(target.id); setTargets((current) => current.filter(({ id }) => id !== target.id)); setNotice('目標武器を削除しました。'); setError(null) } catch (caught: unknown) { setError(caught instanceof ReferencedEntityDeleteError ? deleteReferenceMessage(caught) : caught instanceof Error ? caught.message : '削除できません。') } }
  const definitions = draft ? master.weaponBonusDefinitions.filter((definition) => definition.isEnabled && definition.weaponTypeId === draft.weaponTypeId && definition.scope === 'gogma_artian') : []
  const bonusTypeIds = [...new Set(definitions.map(({ bonusTypeId }) => bonusTypeId))]
  const firstChoice = () => { const definition = definitions[0]; if (!definition) throw new MasterOptionsUnavailableError('復元ボーナスのマスターデータが利用できません。'); return { bonusTypeId: definition.bonusTypeId, minimumRankId: definition.bonusRankId } }
  const updateCondition = (index: number, condition: BonusCondition) => { if (!draft) return; const next = [...draft.practicalBonusConditions]; next[index] = condition; setDraft({ ...draft, practicalBonusConditions: next }) }
  const updateGroup = (index: number, group: AlternativeBonusConditionGroup) => { if (!draft) return; const next = [...draft.practicalAlternativeGroups]; next[index] = group; setDraft({ ...draft, practicalAlternativeGroups: next }) }
  return <PageShell title="目標武器" description="欲しい完成武器の理想条件と実用条件を管理します。"><Stack spacing={2}><MasterDataStatusAlert master={master} />{loading && <LinearProgress />}{error && <Alert severity="error">{error}</Alert>}{notice && <Alert severity="success">{notice}</Alert>}<Button variant="contained" onClick={openNew}>目標武器を追加</Button>{!loading && targets.length === 0 && <Alert severity="info">目標武器は未登録です。</Alert>}{targets.map((target) => <Paper key={target.id} variant="outlined" sx={{ p: 2 }}><Stack spacing={1}><Typography variant="h3">{target.name}</Typography><Typography>{weaponTypes.find(({ id }) => id === target.weaponTypeId)?.displayNameJa} / {elements.find(({ id }) => id === target.elementId)?.displayNameJa} ／ 優先度 {target.priority} ／ {target.isEnabled ? '有効' : '無効'}</Typography><Typography variant="body2">理想: 5枠設定済み</Typography><Typography variant="body2">実用: 条件 {target.practicalBonusConditions.length}件、代替グループ {target.practicalAlternativeGroups.length}件</Typography><Stack direction="row"><Button onClick={() => openEdit(target)}>編集</Button><Button color="error" onClick={() => void remove(target)}>削除</Button></Stack></Stack></Paper>)}
    <Dialog open={draft !== null} onClose={() => setDraft(null)} fullWidth maxWidth="lg"><DialogTitle>{editing ? '目標武器を編集' : '目標武器を追加'}</DialogTitle>{draft && <DialogContent><Stack spacing={3} sx={{ pt: 1 }}><TextField label="名前" required value={draft.name} onChange={(event) => setDraft({ ...draft, name: event.target.value })} /><Stack direction={{ xs: 'column', sm: 'row' }} spacing={1}><FormControl fullWidth><InputLabel id="target-weapon-type">武器種</InputLabel><Select labelId="target-weapon-type" label="武器種" value={draft.weaponTypeId} onChange={(event) => { try { setDraft({ ...draft, weaponTypeId: event.target.value, idealBonuses: createDefaultBonusSet(master, event.target.value), practicalBonusConditions: [], practicalAlternativeGroups: [] }) } catch (caught) { if (caught instanceof MasterOptionsUnavailableError) setError(caught.message) } }}>{weaponTypes.map((type) => <MenuItem key={type.id} value={type.id}>{type.displayNameJa}</MenuItem>)}</Select></FormControl><FormControl fullWidth><InputLabel id="target-element">属性</InputLabel><Select labelId="target-element" label="属性" value={draft.elementId} onChange={(event) => setDraft({ ...draft, elementId: event.target.value })}>{elements.map((element) => <MenuItem key={element.id} value={element.id}>{element.displayNameJa}</MenuItem>)}</Select></FormControl><FormControl fullWidth><InputLabel id="target-priority">優先度</InputLabel><Select labelId="target-priority" label="優先度" value={draft.priority} onChange={(event) => setDraft({ ...draft, priority: Number(event.target.value) as TargetWeapon['priority'] })}>{[1,2,3,4,5].map((value) => <MenuItem key={value} value={value}>{value}</MenuItem>)}</Select></FormControl></Stack><FormControlLabel control={<Checkbox checked={draft.isEnabled} onChange={(event) => setDraft({ ...draft, isEnabled: event.target.checked })} />} label="有効" /><BonusSetEditor label="理想の復元ボーナス5枠" master={master} weaponTypeId={draft.weaponTypeId} scope="gogma_artian" value={draft.idealBonuses} onChange={(idealBonuses) => setDraft({ ...draft, idealBonuses })} />
      <Stack spacing={1}><Typography variant="h3">実用ボーナス条件</Typography>{draft.practicalBonusConditions.map((condition, index) => { const ranks = getRanksForBonusType(master, draft.weaponTypeId, condition.bonusTypeId, 'gogma_artian'); return <Paper key={condition.id} variant="outlined" sx={{ p: 2 }}><Stack spacing={1}><FormControl><InputLabel id={`condition-${index}-type`}>ボーナス種別</InputLabel><Select labelId={`condition-${index}-type`} label="ボーナス種別" value={condition.bonusTypeId} onChange={(event) => { const nextRanks = getRanksForBonusType(master, draft.weaponTypeId, event.target.value, 'gogma_artian'); updateCondition(index, { ...condition, bonusTypeId: event.target.value, minimumRankId: nextRanks[0]?.id ?? '' }) }}>{bonusTypeIds.map((id) => <MenuItem key={id} value={id}>{master.bonusTypes.find((type) => type.id === id)?.displayNameJa}</MenuItem>)}</Select></FormControl><FormControl><InputLabel id={`condition-${index}-rank`}>最低ランク</InputLabel><Select labelId={`condition-${index}-rank`} label="最低ランク" value={condition.minimumRankId} onChange={(event) => updateCondition(index, { ...condition, minimumRankId: event.target.value })}>{ranks.map((rank) => <MenuItem key={rank.id} value={rank.id}>{rank.displayNameJa}</MenuItem>)}</Select></FormControl><TextField label="必要個数" type="number" value={condition.requiredCount} slotProps={{ htmlInput: { min: 1, max: 5 } }} onChange={(event) => updateCondition(index, { ...condition, requiredCount: Number(event.target.value) })} /><TextField label="必要EX個数" type="number" value={condition.requiredExCount} slotProps={{ htmlInput: { min: 0, max: condition.requiredCount } }} onChange={(event) => updateCondition(index, { ...condition, requiredExCount: Number(event.target.value) })} /><Button color="error" onClick={() => setDraft({ ...draft, practicalBonusConditions: draft.practicalBonusConditions.filter((_, itemIndex) => itemIndex !== index) })}>条件を削除</Button></Stack></Paper>})}<Button onClick={() => { try { const choice = firstChoice(); setDraft({ ...draft, practicalBonusConditions: [...draft.practicalBonusConditions, { id: randomItemId(), ...choice, requiredCount: 1, requiredExCount: 0 }] }) } catch (caught) { if (caught instanceof Error) setError(caught.message) } }}>条件を追加</Button></Stack>
      <Stack spacing={1}><Typography variant="h3">代替ボーナスグループ</Typography>{draft.practicalAlternativeGroups.map((group, groupIndex) => <Paper key={group.id} variant="outlined" sx={{ p: 2 }}><Stack spacing={1}><Typography>次のいずれかを合計</Typography><TextField label="グループの必要個数" type="number" value={group.requiredCount} slotProps={{ htmlInput: { min: 1, max: 5 } }} onChange={(event) => updateGroup(groupIndex, { ...group, requiredCount: Number(event.target.value) })} />{group.options.map((option, optionIndex) => { const ranks = getRanksForBonusType(master, draft.weaponTypeId, option.bonusTypeId, 'gogma_artian'); return <Stack key={optionIndex} direction={{ xs: 'column', sm: 'row' }} spacing={1}><FormControl fullWidth><InputLabel id={`group-${groupIndex}-option-${optionIndex}-type`}>選択肢のボーナス種別</InputLabel><Select labelId={`group-${groupIndex}-option-${optionIndex}-type`} label="選択肢のボーナス種別" value={option.bonusTypeId} onChange={(event) => { const nextOptions = [...group.options]; const nextRanks = getRanksForBonusType(master, draft.weaponTypeId, event.target.value, 'gogma_artian'); nextOptions[optionIndex] = { bonusTypeId: event.target.value, minimumRankId: nextRanks[0]?.id ?? '' }; updateGroup(groupIndex, { ...group, options: nextOptions }) }}>{bonusTypeIds.map((id) => <MenuItem key={id} value={id}>{master.bonusTypes.find((type) => type.id === id)?.displayNameJa}</MenuItem>)}</Select></FormControl><FormControl fullWidth><InputLabel id={`group-${groupIndex}-option-${optionIndex}-rank`}>選択肢の最低ランク</InputLabel><Select labelId={`group-${groupIndex}-option-${optionIndex}-rank`} label="選択肢の最低ランク" value={option.minimumRankId} onChange={(event) => { const nextOptions = [...group.options]; nextOptions[optionIndex] = { ...option, minimumRankId: event.target.value }; updateGroup(groupIndex, { ...group, options: nextOptions }) }}>{ranks.map((rank) => <MenuItem key={rank.id} value={rank.id}>{rank.displayNameJa}</MenuItem>)}</Select></FormControl><Button color="error" disabled={group.options.length === 1} onClick={() => updateGroup(groupIndex, { ...group, options: group.options.filter((_, index) => index !== optionIndex) })}>選択肢を削除</Button></Stack>})}<Button onClick={() => { try { updateGroup(groupIndex, { ...group, options: [...group.options, firstChoice()] }) } catch (caught) { if (caught instanceof Error) setError(caught.message) } }}>選択肢を追加</Button><Button color="error" onClick={() => setDraft({ ...draft, practicalAlternativeGroups: draft.practicalAlternativeGroups.filter((_, index) => index !== groupIndex) })}>グループを削除</Button></Stack></Paper>)}<Button onClick={() => { try { setDraft({ ...draft, practicalAlternativeGroups: [...draft.practicalAlternativeGroups, { id: randomItemId(), requiredCount: 1, options: [firstChoice()] }] }) } catch (caught) { if (caught instanceof Error) setError(caught.message) } }}>代替グループを追加</Button></Stack>
      <SkillConditionEditor label="理想スキル条件" master={master} value={draft.idealSkillCondition} onChange={(idealSkillCondition) => setDraft({ ...draft, idealSkillCondition })} /><SkillConditionEditor label="実用スキル条件" master={master} value={draft.practicalSkillCondition} onChange={(practicalSkillCondition) => setDraft({ ...draft, practicalSkillCondition })} /><TextField label="メモ" multiline value={draft.memo ?? ''} onChange={(event) => setDraft({ ...draft, memo: event.target.value || null })} /></Stack></DialogContent>}<DialogActions><Button onClick={() => setDraft(null)}>キャンセル</Button><Button variant="contained" onClick={() => void save()}>保存</Button></DialogActions></Dialog>
  </Stack></PageShell>
}
